.ORIG x3100

   LD R1,X       ;LOAD X INTO R1
   LD R2,Y       ;LOAD Y INTO R2
   ADD R3,R1,R2   ;SUM
   ST R3,SUM   ;STORE SUM
   AND R3,R1,R2   ;AND
   ST R3,AAND   ;STORE AND
   NOT R3,R1   ;NOT X
   ST R3,NOTX   ;STORE NOTX
   NOT R4,R2   ;NOT Y
   ST R4,NOTY   ;STORE NOTY
   AND R3,R3,R4   ;X' AND Y'
   NOT R3,R3   ;(X' AND Y')'=X OR Y
   ST R3,OOR   ;STORE OR
   ADD R3,R1,#3   ;X+3
   ST R3,XPLUS3   ;STORE X+3
   ADD R3,R2,#-3   ;Y-3
   ST R3,YMINUS3   ;STORE Y-3
   AND R3,R1,#0001   ;CHECK EVEN OR ODD
   ST R3,Z       
   HALT
   
X   .FILL x25
Y   .FILL x12
SUM   .FILL #0
AAND   .FILL #0
OOR   .FILL #0
NOTX   .FILL #0
NOTY   .FILL #0
XPLUS3   .FILL #0
YMINUS3   .FILL #0
Z   .FILL #0

   .END